#!/bin/bash

# Configuration
APP_NAME="SwiftUIAPP"
HARBOUR_PATH="../../../harbour"
FIVEMAC_PATH="../.."
SDK_PATH=$(xcrun --show-sdk-path)

echo "Building $APP_NAME..."

# 1. Clean previous build
rm -rf "$APP_NAME.app"
rm -f *.o *.c *.d

# 2. Build the Library First
echo "== Building SwiftFive Library =="
cd SwiftFive
./build_lib.sh
if [ $? -ne 0 ]; then echo "Library build failed"; exit 1; fi
cd ..
echo "== Library Built =="

# 3. Compile App (TestSwiftImage.prg)
echo "Compiling App..."
echo "Compiling 'TestSwiftImage.prg'..."
"$HARBOUR_PATH/bin/harbour" TestSwiftImage.prg -n -I"SwiftFive/include" -I"$FIVEMAC_PATH/include" -I"$HARBOUR_PATH/include"

echo "Compiling C generated by Harbour..."
clang -c TestSwiftImage.c -I"$FIVEMAC_PATH/include" -I"$HARBOUR_PATH/include" -o TestSwiftImage.o

echo "Linking..."
if [ ! -d "$APP_NAME.app/Contents/MacOS" ]; then
    mkdir -p "$APP_NAME.app/Contents/MacOS"
fi
  
# Setup Frameworks for Linking
FRAMEWORKS="-framework Cocoa -framework SwiftUI -framework WebKit -framework AVFoundation -framework AVKit -framework CoreMedia -framework ScreenCaptureKit -framework UserNotifications -framework UniformTypeIdentifiers -framework ScriptingBridge"
HARBOUR_LIBS="-L$HARBOUR_PATH/lib -lhbdebug -lhbvm -lhbrtl -lhblang -lhbrdd -lgttrm -lhbmacro -lhbpp -lrddntx -lrddcdx -lrddfpt -lhbsix -lhbcommon -lhbcplr -lhbcpage -lhbhsx -lrddnsx"
FIVEMAC_LIBS="-L$FIVEMAC_PATH/lib -lfive -lfivec"

# Link with our NEW library
# Note: we need to link against the Swift library logic.
# Since we archived everything into libSwiftFive.a, we link that.
# Crucial: We must also link Swift Runtime logic. Since we are not compiling swift here, we use swiftc for linking OR use clang with -L/usr/lib/swift stuff. 
# Using swiftc is easiest to ensure swift libs are found.

swiftc -o "$APP_NAME.app/Contents/MacOS/$APP_NAME" \
    TestSwiftImage.o \
    -L"SwiftFive/lib" -Xlinker -force_load -Xlinker SwiftFive/lib/libSwiftFive.a \
    -L"$SDK_PATH/usr/lib" \
    $FIVEMAC_LIBS \
    $HARBOUR_LIBS \
    $FRAMEWORKS \
    -Xlinker -rpath -Xlinker @executable_path/../Frameworks

if [ $? -ne 0 ]; then
    echo "Linking failed"
    exit 1
fi

# 5. Create Info.plist
echo "Creating Info.plist..."
mkdir -p "$APP_NAME.app/Contents"
PLIST="$APP_NAME.app/Contents/Info.plist"

echo '<?xml version="1.0" encoding="UTF-8"?>' > "$PLIST"
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$PLIST"
echo '<plist version="1.0">' >> "$PLIST"
echo '<dict>' >> "$PLIST"
echo '    <key>CFBundleExecutable</key>' >> "$PLIST"
echo '    <string>'$APP_NAME'</string>' >> "$PLIST"
echo '    <key>CFBundleIdentifier</key>' >> "$PLIST"
echo '    <string>com.fivetech.'$APP_NAME'</string>' >> "$PLIST"
echo '    <key>CFBundleName</key>' >> "$PLIST"
echo '    <string>'$APP_NAME'</string>' >> "$PLIST"
echo '    <key>NSHighResolutionCapable</key>' >> "$PLIST"
echo '    <true/>' >> "$PLIST"
echo '</dict>' >> "$PLIST"
echo '</plist>' >> "$PLIST"

echo "Build done! Run with: open $APP_NAME.app"
chmod +x build.sh
