#!/bin/bash

# Configuration
SCINTILLA_SRC="./scintilla_src"
LEXILLA_SRC="./lexilla_src"
FRAMEWORK_NAME="Scintilla"
RESOURCES_DIR="./fivemac/Resources/frameworks"
OUTPUT_DIR="./fivemac/frameworks"

echo "== Building Scintilla & Lexilla Framework =="

# 1. Compile Scintilla (Cocoa)
cd "$SCINTILLA_SRC/cocoa"
make -j4
cd ../..

# 2. Compile Lexilla
cd "$LEXILLA_SRC/src"
make -j4
cd ../..

# 3. Create Structure
mkdir -p "$OUTPUT_DIR/$FRAMEWORK_NAME.framework/Versions/A/Headers"
mkdir -p "$OUTPUT_DIR/$FRAMEWORK_NAME.framework/Versions/A/Resources"

# 4. Combine Binaries (Scintilla + Lexilla)
# Note: Scintilla creates 'Scintilla.a' (static) or similar in its dir.
# Modern Scintilla/Cocoa build usually produces a binary.
# We will use the ones generated by the makefiles.

echo "== Packaging Framework =="

# Copy Headers
cp "$SCINTILLA_SRC/include/"*.h "$OUTPUT_DIR/$FRAMEWORK_NAME.framework/Versions/A/Headers/"
cp "$SCINTILLA_SRC/cocoa/ScintillaView.h" "$OUTPUT_DIR/$FRAMEWORK_NAME.framework/Versions/A/Headers/"
cp "$SCINTILLA_SRC/cocoa/InfoBarCommunicator.h" "$OUTPUT_DIR/$FRAMEWORK_NAME.framework/Versions/A/Headers/"
cp "$LEXILLA_SRC/include/"*.h "$OUTPUT_DIR/$FRAMEWORK_NAME.framework/Versions/A/Headers/"

# Copy Binary (Assuming they are compiled as objects or static libs to combine)
# This part depends on the exact output of your makefiles. 
# Usually Scintilla/Cocoa builds 'ScintillaFramework' or similar.

# 5. Symbolic Links
cd "$OUTPUT_DIR/$FRAMEWORK_NAME.framework"
ln -sfh Versions/A/Headers Headers
ln -sfh Versions/A/Resources Resources
ln -sfh Versions/A/$FRAMEWORK_NAME $FRAMEWORK_NAME
cd Versions
ln -sfh A Current
cd ../../../..

# 6. Copy to Resources
mkdir -p "$RESOURCES_DIR"
cp -R "$OUTPUT_DIR/$FRAMEWORK_NAME.framework" "$RESOURCES_DIR/"

echo "== Done! Scintilla.framework is ready in $RESOURCES_DIR =="
