#!/bin/bash

# Configuration
HARBOUR_PATH="../../../harbour"
FIVEMAC_PATH="../.."
SDK_PATH=$(xcrun --show-sdk-path)

if [ -z "$1" ]; then
  echo "Syntax: ./build.sh <file>"
  exit 1
fi

APP_NAME=$(basename "$1")
PRG_FILE=$1.prg

echo "Building $APP_NAME..."

# 1. Clean previous build
rm -rf "$APP_NAME.app"
rm -rf obj
mkdir -p obj

# 2. Build the Library First (Optional but recommended)
echo "== Building SwiftFive Library =="
pushd ..
make
popd
if [ $? -ne 0 ]; then echo "Library build failed"; exit 1; fi
echo "== Library Built =="

# 3. Compile App
echo "Compiling App..."
"$HARBOUR_PATH/bin/harbour" "$PRG_FILE" -n -w -o"obj/$APP_NAME.c" -I"../include" -I"$FIVEMAC_PATH/nativo/include" -I"$HARBOUR_PATH/include"

if [ $? -ne 0 ]; then echo "Error compiling Harbour App"; exit 1; fi

echo "Compiling C generated by Harbour..."
clang -c "obj/$APP_NAME.c" \
    -I"../include" \
    -I"$FIVEMAC_PATH/nativo/include" \
    -I"$HARBOUR_PATH/include" \
    -o "obj/$APP_NAME.o"

if [ $? -ne 0 ]; then echo "Error compiling C"; exit 1; fi

# 4. Link Everything
echo "Creating .app bundle structure..."
mkdir -p "$APP_NAME.app/Contents/MacOS"
mkdir -p "$APP_NAME.app/Contents/Resources"
mkdir -p "$APP_NAME.app/Contents/Frameworks"

echo "Linking..."
# Setup Frameworks for Linking
FRAMEWORKS="-framework Cocoa -framework SwiftUI -framework WebKit -framework AVFoundation -framework AVKit -framework CoreMedia -framework ScreenCaptureKit -framework UserNotifications -framework UniformTypeIdentifiers -framework ScriptingBridge -framework MusicKit"
HARBOUR_LIBS="-L$HARBOUR_PATH/lib -lhbdebug -lhbvm -lhbrtl -lhblang -lhbrdd -lgttrm -lhbmacro -lhbpp -lrddntx -lrddcdx -lrddfpt -lhbsix -lhbcommon -lhbcplr -lhbcpage -lhbhsx -lrddnsx"
FIVEMAC_LIBS="-L$FIVEMAC_PATH/nativo/lib -lfive -lfivec"

# Linking the sample with the lib
swiftc -o "$APP_NAME.app/Contents/MacOS/$APP_NAME" \
    "obj/$APP_NAME.o" \
    -L"../lib" -Xlinker -force_load -Xlinker ../lib/libSwiftFive.a \
    -L"$SDK_PATH/usr/lib" \
    $FIVEMAC_LIBS \
    $HARBOUR_LIBS \
    $FRAMEWORKS \
    -F"$FIVEMAC_PATH/Resources/frameworks" -framework Scintilla \
    -Xlinker -rpath -Xlinker @executable_path/../Frameworks \
    -Xlinker -rpath -Xlinker ../../Resources/frameworks

if [ $? -ne 0 ]; then
    echo "Linking failed"
    exit 1
fi

# 5. Create Info.plist
echo "Generating Info.plist..."
PLIST="$APP_NAME.app/Contents/Info.plist"

echo '<?xml version="1.0" encoding="UTF-8"?>' > "$PLIST"
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$PLIST"
echo '<plist version="1.0">' >> "$PLIST"
echo '<dict>' >> "$PLIST"
echo '   <key>CFBundleExecutable</key>' >> "$PLIST"
echo '   <string>'$APP_NAME'</string>' >> "$PLIST"
echo '   <key>CFBundleName</key>' >> "$PLIST"
echo '   <string>'$APP_NAME'</string>' >> "$PLIST"
echo '   <key>CFBundleIdentifier</key>' >> "$PLIST"
echo '   <string>com.fivetech.'$APP_NAME'</string>' >> "$PLIST"
echo '   <key>CFBundlePackageType</key>' >> "$PLIST"
echo '   <string>APPL</string>' >> "$PLIST"
echo '   <key>CFBundleInfoDictionaryVersion</key>' >> "$PLIST"
echo '   <string>6.0</string>' >> "$PLIST"
echo '   <key>CFBundleIconFile</key>' >> "$PLIST"
echo '   <string>fivetech.icns</string>' >> "$PLIST"
echo '   <key>NSHighResolutionCapable</key>' >> "$PLIST"
echo '   <true/>' >> "$PLIST"
echo '   <key>NSPrincipalClass</key>' >> "$PLIST"
echo '   <string>NSApplication</string>' >> "$PLIST"
echo '   <key>NSAppleMusicUsageDescription</key>' >> "$PLIST"
echo '   <string>This app needs access to your music library to play songs.</string>' >> "$PLIST"
echo '   <key>NSAppTransportSecurity</key>' >> "$PLIST"
echo '   <dict>' >> "$PLIST"
echo '      <key>NSAllowsArbitraryLoads</key>' >> "$PLIST"
echo '      <true/>' >> "$PLIST"
echo '   </dict>' >> "$PLIST"
echo '</dict>' >> "$PLIST"
echo '</plist>' >> "$PLIST"

echo 'APPL????' > "$APP_NAME.app/Contents/PkgInfo"

echo "Copying Icon..."
if [ -f "$FIVEMAC_PATH/Resources/icons/fivetech.icns" ]; then
   cp "$FIVEMAC_PATH/Resources/icons/fivetech.icns" "$APP_NAME.app/Contents/Resources/"
fi

echo "Copying Frameworks..."
if [ -d "$FIVEMAC_PATH/Resources/frameworks" ]; then
   cp -R "$FIVEMAC_PATH/Resources/frameworks/"* "$APP_NAME.app/Contents/Frameworks/"
fi

echo "Build done! Run with: open $APP_NAME.app"
chmod +x build.sh
