#include "FiveMac.ch"

static oWnd, oBrw, aPrgs := {}
static cProjectName := "myproject"

function Main()

   local oBtnAdd, oBtnDel, oBtnGen, oBtnBuild, oBtnExit, oBtnLoad, oBtnRun
   local oGet, oGetVer, oGetIcon
   local cVersion := "1.0"
   local cIcon := "fivetech.icns"

   // Removed FLIPPED, Added standard window style, fixed size (not resizable logic usually implied by lack of RESIZE clause or fixed size)
   // In FiveMac, standard windows are resizable unless specific style bits used?
   // Let's keep it simple. If "NO RESIZABLE" isn't a command, we just avoid "MAXIMIZED".
   // "FLIPPED" is useful for coordinate system (Top, Left). Keep it.
   
   // Standard Coordinates (Bottom-Left is 0,0)
   // Height 550 (Increased to lower top elements visually)
   
   DEFINE DIALOG oWnd TITLE "Simple Project Builder" ;
      SIZE 600, 550  FLIPPED

   // --- Top: Inputs (Y=30..90) ---
   @ 30, 30 SAY "Project Name:" OF oWnd SIZE 100, 20
   @ 30, 130 GET oGet VAR cProjectName OF oWnd SIZE 200, 24

   @ 60, 30 SAY "Version:" OF oWnd SIZE 60, 20
   @ 60, 90 GET oGetVer VAR cVersion OF oWnd SIZE 60, 24
   
   @ 60, 160 SAY "Icon:" OF oWnd SIZE 40, 20
   @ 60, 200 GET oGetIcon VAR cIcon OF oWnd SIZE 130, 24

   // --- Middle: Browse (Y=110..380) ---
   @ 110, 30 BROWSE oBrw OF oWnd SIZE 340, 280 ;
      FIELDS aPrgs[ oBrw:nArrayAt ] ;
      HEADERS "Source Files" ;
      COLSIZES 320 

   oBrw:SetArray( aPrgs )
   oBrw:cAlias := "_ARRAY" 
   
   // --- Right Side Buttons (Y=110..270) ---
   @ 110, 400 BUTTON oBtnLoad PROMPT "Load Project" OF oWnd ;
      ACTION LoadHbp( oGet, oBtnGen, oBtnBuild, oBtnRun ) SIZE 160, 24

   @ 150, 400 BUTTON oBtnGen PROMPT "Generate Project" OF oWnd ;
      ACTION GenerateHbp() SIZE 160, 24

   @ 190, 400 BUTTON oBtnBuild PROMPT "Create App" OF oWnd ;
      ACTION BuildApp( cVersion, cIcon, oBtnRun ) SIZE 160, 24
      
   @ 230, 400 BUTTON oBtnRun PROMPT "Launch App" OF oWnd ;
      ACTION RunApp() SIZE 160, 24
      
   oBtnGen:Disable()
   oBtnBuild:Disable()
   oBtnRun:Disable()

   // --- Bottom: Buttons (Y=420) ---
   @ 420, 30 BUTTON oBtnAdd PROMPT "+" OF oWnd ;
      ACTION AddPrg( oBtnGen, oBtnBuild ) SIZE 40, 24

   @ 420, 80 BUTTON oBtnDel PROMPT "-" OF oWnd ;
      ACTION DelPrg( oBtnGen, oBtnBuild ) SIZE 40, 24

   @ 480, 400 BUTTON oBtnExit PROMPT "Exit" OF oWnd ;
      ACTION oWnd:End() SIZE 160, 24

   ACTIVATE DIALOG oWnd CENTERED ;
      ON INIT WndSetResizable( oWnd:hWnd, .F. )
   
return nil

// Helper to check buttons state
function CheckButtons( oBtnGen, oBtnBuild )
   if Len( aPrgs ) > 0
      oBtnGen:Enable()
      oBtnBuild:Enable()
   else
      oBtnGen:Disable()
      oBtnBuild:Disable()
   endif
return nil

function AddPrg( oBtnGen, oBtnBuild )
   local cFile := cGetFile( "PRG files (*.prg)|*.prg", "Select PRG file" )
   local cName
   
   if ! Empty( cFile )
      cName := cFileNoPath( cFile )
      
      if AScan( aPrgs, cName ) > 0
         MsgAlert( "File already in list: " + cName )
         return nil
      endif

      // Store just the filename 
      AAdd( aPrgs, cName )
      oBrw:SetArray( aPrgs )
      oBrw:Refresh()
      
      CheckButtons( oBtnGen, oBtnBuild )
   endif
return nil

function DelPrg( oBtnGen, oBtnBuild )
   local nAt := oBrw:nArrayAt
   if Len( aPrgs ) > 0 .and. nAt > 0
      ADel( aPrgs, nAt )
      ASize( aPrgs, Len( aPrgs ) - 1 )
      oBrw:SetArray( aPrgs )
      oBrw:Refresh()
      
      CheckButtons( oBtnGen, oBtnBuild )
   endif
return nil

function GenerateHbp()
   local cHbpContent := ""
   local cFileHbp := cProjectName + ".hbp"
   local cPath := ""
   local nAt := 0
   local n := 0
   local aFrameworks := {}


   if Empty( cProjectName )
      MsgAlert( "Please enter a project name" )
      return nil
   endif
   
   cPath := ChooseFolder( "Select Project Folder" )
   
   if Empty( cPath )
      return nil
   endif
   
   cFileHbp := cPath + "/" + cProjectName + ".hbp"

   if File( cFileHbp )
      if ! MsgNoYes( "File " + cProjectName + ".hbp already exists. Overwrite?" )
         return nil
      endif
      FErase( cFileHbp )
   endif

   // Basic Template
   cHbpContent += "# Generated by Simple Builder" + CRLF
   cHbpContent += "-n" + CRLF
   cHbpContent += "-w" + CRLF
   
   // Desde linea de comandos aqui no van
  // cHbpContent += "-plat=macos" + CRLF
  // cHbpContent += "-comp=clang" + CRLF


   // Adjust include/lib paths relative to the selected folder? 
   // For now, we assume standard position or use absolute paths?
   // Better to use relative paths if we assume the user is creating projects in 'samples' or similar depth.
   // But allowing any folder makes relative paths broken. 
   // Let's stick to the current relative paths but warn the user or assume they know structure?
   // Or better: Use hardcoded paths to FiveMac for now since this is a "Simple" builder for this repo.
   
   cHbpContent += "-i../include" + CRLF
   cHbpContent += "-i../../harbour/include" + CRLF
   cHbpContent += "-L../lib" + CRLF
   cHbpContent += "-L../../harbour/lib" + CRLF
   cHbpContent += "-lfive" + CRLF
   cHbpContent += "-lfivec" + CRLF
   cHbpContent += "-lz" + CRLF
   cHbpContent += "-lpcre" + CRLF
   cHbpContent += "-lsqlite3" + CRLF
   

   // Frameworks
   cHbpContent += "# Framweworks flags for ObjC" + CRLF
   
   aFrameworks := { "Cocoa","WebKit","IOKit","ScreenCaptureKit","Quartz","CoreImage",;
                    "UserNotifications","ScriptingBridge","AVKit","AVFoundation","CoreMedia","UniformTypeIdentifiers" }    
    
   cHbpContent += "-ldflag=-F../frameworks" + CRLF
 
   for nAt = 1 to Len( aFrameworks )
      cHbpContent += "-ldflag=-framework" + CRLF
      cHbpContent += "-ldflag=" + aFrameworks[ nAt ] + CRLF
   endfor

   // Scintilla 
   cHbpContent += "# Scintilla flags for ObjC" + CRLF

   cHbpContent += "-ldflag=-framework" + CRLF
   cHbpContent += "-ldflag=Scintilla" + CRLF

   // RPath and GT
   cHbpContent += "# RPath flags for ObjC" + CRLF

   cHbpContent += "-ldflag=-rpath" + CRLF
   cHbpContent += "-ldflag=@loader_path/../frameworks" + CRLF
   cHbpContent += "-gtstd" + CRLF
   
   // Output
   cHbpContent += "-o" + cProjectName + CRLF
   
   cHbpContent += "# Helper flags for ObjC" + CRLF
   cHbpContent += "-cflag=-x" + CRLF
   cHbpContent += "-cflag=objective-c" + CRLF

   // Sources
   cHbpContent += "# Sources" + CRLF
   for n := 1 to Len( aPrgs )
      cHbpContent += aPrgs[ n ] + CRLF
   next
   
   // Write file
   // Write file
   if ! MemoWrit( cFileHbp, cHbpContent )
      MsgAlert( "Error writing file: " + cFileHbp )
      return nil
   endif
   
   if ! File( cFileHbp )
      MsgAlert( "File verify failed: " + cFileHbp )
      return nil
   endif

   MsgInfo( "Created successfully: " + cFileHbp )
   
   // Set current dir to that folder for the build process
   DirChange( cPath )

return nil

function BuildApp( cVersion, cIcon, oBtnRun )
   local cCommand, cAppPath, cResPath, cMacPath, cFwPath
   local cHbmk2 := "../../harbour/bin/hbmk2"
   local cPlist, cCode
   local aFiles, n, cFile, cContent, aImages, cImg, cSrcImg
   local cRoot := ".."  // Assumes we are in samples or parallel depth
   local nVerAt, cVerLine

   DEFAULT cVersion := "1.0"
   DEFAULT cIcon := "fivetech.icns"

   if Empty( cProjectName )
      MsgAlert( "Please enter a project name" )
      return nil
   endif

   if ! File( cProjectName + ".hbp" )
      MsgAlert( "Please Generate Project first (HBP not found)" )
      return nil
   endif

   if ! File( cHbmk2 )
      if ! File( cHbmk2 )
         MsgAlert( "Error: hbmk2 not found at " + cHbmk2 )
         return nil
      endif
   endif

   // 1. Compile
   // 1. Compile
   // TaskExec (FiveMac) uses NSTask. Requires absolute path usually or strict path.
   // It returns the output (stdout/stderr).
   // We must pass args as an array.
   
   // Resolve hbmk2 to absolute path for NSTask safety
   // Assuming simple_builder running from samples folder, and hbmk2 is at ../../harbour/bin/hbmk2
   // CurDir() returns current dir (which is set to project dir in GenerateHbp)
   // But we need the path relative to where we started?
   // Actually cHbmk2 is defined as "../../harbour/bin/hbmk2".
   // Let's try passing it directly. If it fails, user will see.
   // Arguments: hbp file, and output flag
   
   cCode := TaskExec( cHbmk2, { cProjectName + ".hbp", "-o" + cProjectName } )

   if ! File( cProjectName )
      MsgAlert( "Build Failed! Output:" + CRLF + cCode )
      return nil
   endif

   // 2. Create Bundle Structure
   cAppPath := cProjectName + ".app"
   cMacPath := cAppPath + "/Contents/MacOS"
   cResPath := cAppPath + "/Contents/Resources"
   cFwPath  := cAppPath + "/Contents/Frameworks"
   
   hb_DirBuild( cAppPath )
   hb_DirBuild( cAppPath + "/Contents" )
   hb_DirBuild( cMacPath )
   hb_DirBuild( cResPath )
   hb_DirBuild( cFwPath )
   
   // 3. Copy Binary
   // CopyFileTo (NSFileManager copyItemAtPath) fails if dest exists. 
   // We must remove it first.
   if File( cMacPath + "/" + cProjectName )
      FErase( cMacPath + "/" + cProjectName )
   endif

   // Using FiveMac CopyFileTo (Cocoa NSFileManager)
   if ! CopyFileTo( cProjectName, cMacPath + "/" + cProjectName )
      MsgAlert( "Error copying binary to bundle" )
      return nil
   endif
   
   // 4. Generate Info.plist
   
   // User passed cVersion from UI.
   
   // Use updated FiveMac function which now includes:
   // - Version support
   // - NSHighResolutionCapable
   // - NSPrincipalClass
   // - NSAppTransportSecurity (AllowsArbitraryLoads)
   CreateInfoFile( cProjectName, cAppPath + "/Contents/", cIcon, cVersion )
   CreatePkInfo( cProjectName, cAppPath )  
   // 5. Copy Resources (Icons & Frameworks)
   
   // Icon Copy relative to ./icons or absolute path
   // CopyFileTo requires full destination path (including filename)
   // Remove dest first
   if File( cIcon )
      if File( cResPath + "/" + cFileNoPath( cIcon ) )
         FErase( cResPath + "/" + cFileNoPath( cIcon ) )
      endif
      CopyFileTo( cIcon, cResPath + "/" + cFileNoPath( cIcon ) )
   else
      if File( cRoot + "/icons/" + cIcon )
         if File( cResPath + "/" + cIcon )
             FErase( cResPath + "/" + cIcon )
         endif
         CopyFileTo( cRoot + "/icons/" + cIcon, cResPath + "/" + cIcon )
      else
         // Fallback default
         if File( cResPath + "/fivetech.icns" )
             FErase( cResPath + "/fivetech.icns" )
         endif
         CopyFileTo( cRoot + "/icons/fivetech.icns", cResPath + "/fivetech.icns" )
      endif
   endif

   WaitRun( "cp -r " + cRoot + "/frameworks/* " + cFwPath + "/" )

   // 6. Smart Image Bundling
   // Scan PRGs for images
   hb_DirBuild( cResPath + "/bitmaps" )
   
   for n := 1 to Len( aPrgs )
      cContent := MemoRead( aPrgs[ n ] )
      // Scanning strings... complex in Harbour without Regex, 
      // but simplistic approach: check if file existing in bitmaps folder is present in string
      
      // Better approach: Iterate all bitmaps in ../bitmaps and check if their name appears in the source
      // This is reverse but safer/easier than parsing quotes
      
      aImages := Directory( cRoot + "/bitmaps/*.*" )
      for each aFiles in aImages
          cImg := aFiles[ 1 ]
          if At( Lower( cImg ), Lower( cContent ) ) > 0 .or. At( Upper( cImg ), Upper( cContent ) ) > 0
             WaitRun( "cp " + cRoot + "/bitmaps/" + cImg + " " + cResPath + "/bitmaps/" )
          endif
      next
   next
   
   MsgInfo( "Build Complete: " + cAppPath )
   
   if oBtnRun != nil
      oBtnRun:Enable()
   endif
   
return nil

function RunApp()
   local cApp := hb_DirBase() + cProjectName + ".app"
   
   if ! File( cApp )
       // Try without hb_DirBase if it failed or if cProjectName is full path?
       cApp := cProjectName + ".app"
   endif
   
   if ! File( cApp )
      MsgAlert( "App not found: " + cApp )
      return nil
   endif
   
   // MacExec is better for launching Apps (GUI)
   MacExec( cApp )
   
return nil

function LoadHbp( oGet, oBtnGen, oBtnBuild, oBtnRun )
   local cFile := cGetFile( "HBP Project (*.hbp)|*.hbp", "Select Project" )
   local cContent, aLines, cLine, n
   local cExt, i
   
   if ! Empty( cFile )
      cProjectName := cFileNoExt( cFileNoPath( cFile ) )
      
      // Change to Project Directory so HBP check passes
      DirChange( cFilePath( cFile ) )
      
      oGet:Refresh()
      
      cContent := MemoRead( cFile )
      aLines := HB_ATokens( cContent, CRLF )
      
      aPrgs := {}
      
      for n := 1 to Len( aLines )
         cLine := AllTrim( aLines[ n ] )
         
         // Skip comments and flags
         if Left( cLine, 1 ) == "#" .or. Left( cLine, 1 ) == "-" .or. Empty( cLine )
            loop
         endif
         
         // Check extension
         cExt := Lower( cFileExt( cLine ) )
         if cExt == "prg" .or. cExt == "c" .or. cExt == "m"
             AAdd( aPrgs, cLine )
         else
             // If valid file, add it
             if ! Empty( cExt )
                AAdd( aPrgs, cLine )
             endif
         endif
      next
      
      oBrw:SetArray( aPrgs )
      oBrw:Refresh()
      
      CheckButtons( oBtnGen, oBtnBuild )
      
      // Check if App exists to enable Run?
      if File( cProjectName + ".app" )
         oBtnRun:Enable()
      else
         oBtnRun:Disable()
      endif
      
      MsgInfo( "Project Loaded: " + cProjectName )
   endif

return nil
