// ui_stubs.c - Stub functions for linking tests without GTK/UI backend
// These provide empty implementations of UI functions referenced by classes.prg

#include "hbapi.h"

// UI stubs - all return nil/nothing
HB_FUNC( UI_GETPROP ) {}
HB_FUNC( UI_SETPROP ) {}
HB_FUNC( UI_ONEVENT ) {}
HB_FUNC( UI_FORMRESULT ) {}
HB_FUNC( UI_FORMSHOW ) {}
HB_FUNC( UI_FORMCLOSE ) {}
HB_FUNC( UI_FORMDESTROY ) {}
HB_FUNC( UI_FORMSETDESIGN ) {}
HB_FUNC( UI_FORMTOJSON ) {}
HB_FUNC( UI_MENUBARCREATE ) {}
HB_FUNC( UI_FORMNEW ) {}
HB_FUNC( UI_FORMRUN ) {}
HB_FUNC( UI_MENUITEMADDEX ) {}
HB_FUNC( UI_MENUSEPADD ) {}
HB_FUNC( UI_LABELNEW ) {}
HB_FUNC( UI_EDITNEW ) {}
HB_FUNC( UI_BUTTONNEW ) {}
HB_FUNC( UI_CHECKBOXNEW ) {}
HB_FUNC( UI_COMBOSETINDEX ) {}
HB_FUNC( UI_COMBOADDITEM ) {}
HB_FUNC( UI_COMBOBOXNEW ) {}
HB_FUNC( UI_GROUPBOXNEW ) {}
HB_FUNC( UI_PALETTEADDTAB ) {}
HB_FUNC( UI_PALETTEADDCOMP ) {}
HB_FUNC( UI_PALETTENEW ) {}
HB_FUNC( UI_TOOLBTNADDSEP ) {}
HB_FUNC( UI_TOOLBARNEW ) {}
HB_FUNC( UI_TOOLBTNADD ) {}
HB_FUNC( UI_TOOLBTNONCLICK ) {}
HB_FUNC( UI_MENUPOPUPADD ) {}
HB_FUNC( UI_MSGBOX ) {}

// SQLite stubs
HB_FUNC( SQLITE3_OPEN ) {}
HB_FUNC( SQLITE3_EXEC ) {}
HB_FUNC( SQLITE3_ERRMSG ) {}
HB_FUNC( SQLITE3_PREPARE ) {}
HB_FUNC( SQLITE3_COLUMN_COUNT ) {}
HB_FUNC( SQLITE3_STEP ) {}
HB_FUNC( SQLITE3_COLUMN_TEXT ) {}
HB_FUNC( SQLITE3_FINALIZE ) {}
