#!/bin/bash

# Configuration
HARBOUR_PATH="../../../harbour"
FIVEMAC_PATH="../.."
SDK_PATH=$(xcrun --show-sdk-path)

# Check Parameter
if [ -z "$1" ]; then
    echo "Usage: ./BuildTest.sh <PRG_NAME_WITHOUT_EXTENSION>"
    echo "Example: ./BuildTest.sh TestSwiftImage"
    exit 1
fi

PRG_NAME="$1"
APP_NAME="$PRG_NAME"
SRC_PRG="$PRG_NAME.prg"

if [ ! -f "$SRC_PRG" ]; then
    echo "Error: File $SRC_PRG not found."
    exit 1
fi

echo "Building $APP_NAME..."

# 1. Clean previous build (only for this app)
rm -rf "$APP_NAME.app"
rm -f "$PRG_NAME.o" "$PRG_NAME.c"

# 2. Build the Library First (Ensure it is up to date)
echo "== Checking SwiftFive Library =="
cd SwiftFive
./build_lib.sh
if [ $? -ne 0 ]; then echo "Library build failed"; exit 1; fi
cd ..
echo "== Library Ready =="

# 3. Compile App
echo "Compiling '$SRC_PRG'..."
"$HARBOUR_PATH/bin/harbour" "$SRC_PRG" -n -I"SwiftFive/include" -I"$FIVEMAC_PATH/include" -I"$HARBOUR_PATH/include"

if [ $? -ne 0 ]; then echo "Error compiling Harbour App"; exit 1; fi

echo "Compiling C generated by Harbour..."
clang -c "$PRG_NAME.c" \
    -I"$FIVEMAC_PATH/include" \
    -I"$HARBOUR_PATH/include" \
    -o "$PRG_NAME.o"

if [ $? -ne 0 ]; then echo "Error compiling C"; exit 1; fi

# 4. Link Everything
echo "Linking..."
if [ ! -d "$APP_NAME.app/Contents/MacOS" ]; then
    mkdir -p "$APP_NAME.app/Contents/MacOS"
fi

# Setup Frameworks for Linking
FRAMEWORKS="-framework Cocoa -framework SwiftUI -framework WebKit -framework AVFoundation -framework AVKit -framework CoreMedia -framework ScreenCaptureKit -framework UserNotifications -framework UniformTypeIdentifiers -framework ScriptingBridge"
HARBOUR_LIBS="-L$HARBOUR_PATH/lib -lhbdebug -lhbvm -lhbrtl -lhblang -lhbrdd -lgttrm -lhbmacro -lhbpp -lrddntx -lrddcdx -lrddfpt -lhbsix -lhbcommon -lhbcplr -lhbcpage -lhbhsx -lrddnsx"
FIVEMAC_LIBS="-L$FIVEMAC_PATH/lib -lfive -lfivec"

swiftc -o "$APP_NAME.app/Contents/MacOS/$APP_NAME" \
    "$PRG_NAME.o" \
    -L"SwiftFive/lib" -Xlinker -force_load -Xlinker SwiftFive/lib/libSwiftFive.a \
    -L"$SDK_PATH/usr/lib" \
    $FIVEMAC_LIBS \
    $HARBOUR_LIBS \
    $FRAMEWORKS \
    -Xlinker -rpath -Xlinker @executable_path/../Frameworks

if [ $? -ne 0 ]; then
    echo "Linking failed"
    exit 1
fi

# 5. Create Info.plist
echo "Creating Info.plist..."
mkdir -p "$APP_NAME.app/Contents"
PLIST="$APP_NAME.app/Contents/Info.plist"

echo '<?xml version="1.0" encoding="UTF-8"?>' > "$PLIST"
echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$PLIST"
echo '<plist version="1.0">' >> "$PLIST"
echo '<dict>' >> "$PLIST"
echo '    <key>CFBundleExecutable</key>' >> "$PLIST"
echo '    <string>'$APP_NAME'</string>' >> "$PLIST"
echo '    <key>CFBundleIdentifier</key>' >> "$PLIST"
echo '    <string>com.fivetech.'$APP_NAME'</string>' >> "$PLIST"
echo '    <key>CFBundleName</key>' >> "$PLIST"
echo '    <string>'$APP_NAME'</string>' >> "$PLIST"
echo '    <key>NSHighResolutionCapable</key>' >> "$PLIST"
echo '    <true/>' >> "$PLIST"
echo '</dict>' >> "$PLIST"
echo '</plist>' >> "$PLIST"

echo "Build done! Run with: open $APP_NAME.app"
