#import <Cocoa/Cocoa.h>
#include <fivemac.h>

// Import the Swift header generated by the build process
#import "SwiftFive-Swift.h"

// Forward declarations of common helper functions
void SwiftMsgAlert(NSString *title, NSString *msg);
void setupSwiftView(NSView *swiftView, id parent, CGFloat x, CGFloat y,
                    CGFloat w, CGFloat h);
NSString *GetRootIdFromParam(int paramIndex);

// Direct bridging Helpers for Factory methods (Internal)
const int8_t *sw_parc(int iParam);
bool sw_parl(int iParam);
const int8_t *sw_GetRootId_par(int iParam);

// --- Bridge Prototypes (Generated by @HarbourBridge) ---
// El prefijo SW_ es añadido automáticamente por la macro.

// Toggle
void SW_TGL_SET_VALUE(const int8_t *id, const int8_t *value);
const int8_t *SW_TGL_GET_VALUE(const int8_t *id);
void SW_TGL_SET_CAPTION(const int8_t *id, const int8_t *caption);
void SW_TGL_SET_COLORS(const int8_t *id, const int8_t *accentHex,
                       const int8_t *textHex);

// VStack
void SW_VSTK_SET_SCROLL(const int8_t *rootId, const int8_t *scrollable);
void SW_VSTK_SET_BGCOLOR_HEX(const int8_t *rootId, const int8_t *hex);
void SW_VSTK_SET_FGCOLOR_HEX(const int8_t *rootId, const int8_t *hex);
void SW_VSTK_SET_SPACING(const int8_t *rootId, const int8_t *spacing);
void SW_VSTK_SET_ALIGNMENT(const int8_t *rootId, const int8_t *alignment);
void SW_VSTK_SET_ITEM_TEXT(const int8_t *rootId, const int8_t *id,
                           const int8_t *text);
void SW_VSTK_SET_ITEM_COLOR_HEX(const int8_t *rootId, const int8_t *id,
                                const int8_t *hex);
void SW_VSTK_SET_ITEM_BGCOLOR_HEX(const int8_t *rootId, const int8_t *id,
                                  const int8_t *hex);
void SW_VSTK_SET_ITEM_LAYOUT(const int8_t *rootId, const int8_t *id,
                             const int8_t *w, const int8_t *h, const int8_t *s);
void SW_VSTK_SET_ITEM_FONT(const int8_t *rootId, const int8_t *id,
                           const int8_t *size, const int8_t *isBold);
void SW_VSTK_SET_ITEM_RADIUS(const int8_t *rootId, const int8_t *id,
                             const int8_t *radius);
void SW_VSTK_SET_INVERTED_COLOR(const int8_t *rootId, const int8_t *inverted);
void SW_VSTK_REMOVE_ALL(const int8_t *rootId);
const int8_t *SW_VSTK_ADD_ITEM(const int8_t *rootId, const int8_t *content);
const int8_t *SW_VSTK_ADD_TEXT_TO(const int8_t *rootId, const int8_t *content,
                                  const int8_t *parentId);
const int8_t *SW_VSTK_ADD_SPACER_TO(const int8_t *rootId,
                                    const int8_t *parentId);
const int8_t *SW_VSTK_ADD_SYSTEM_IMAGE_TO(const int8_t *rootId,
                                          const int8_t *systemName,
                                          const int8_t *parentId);
const int8_t *SW_VSTK_ADD_HSTACK(const int8_t *rootId, const int8_t *parentId);
const int8_t *SW_VSTK_ADD_VSTACK(const int8_t *rootId, const int8_t *parentId);
const int8_t *SW_VSTK_ADD_BUTTON_ITEM(const int8_t *rootId, const int8_t *text,
                                      const int8_t *parentId);
const int8_t *SW_VSTK_ADD_BATCH(const int8_t *rootId, const int8_t *json,
                                const int8_t *parentId);
const int8_t *SW_VSTK_ADD_LIST(const int8_t *rootId, const int8_t *parentId);
const int8_t *SW_VSTK_ADD_LAZYVGRID(const int8_t *rootId,
                                    const int8_t *parentId,
                                    const int8_t *columnsJson);
const int8_t *SW_VSTK_ADD_DIVIDER_TO(const int8_t *rootId,
                                     const int8_t *parentId);
const int8_t *SW_VSTK_GET_LAST_ITEM_ID(const int8_t *rootId);

// ZStack
void SW_ZSTK_SET_ALIGNMENT(const int8_t *rootId, const int8_t *alignment);
void SW_ZSTK_SET_BGCOLOR_HEX(const int8_t *rootId, const int8_t *hex);
void SW_ZSTK_SET_FGCOLOR_HEX(const int8_t *rootId, const int8_t *hex);
void SW_ZSTK_SET_ITEM_COLOR_HEX(const int8_t *rootId, const int8_t *id,
                                const int8_t *hex);
void SW_ZSTK_SET_ITEM_BGCOLOR_HEX(const int8_t *rootId, const int8_t *id,
                                  const int8_t *hex);
void SW_ZSTK_REMOVE_ALL(const int8_t *rootId);
const int8_t *SW_ZSTK_ADD_ITEM(const int8_t *rootId, const int8_t *content);
const int8_t *SW_ZSTK_ADD_FILE_IMAGE(const int8_t *rootId,
                                     const int8_t *filePath);
const int8_t *SW_ZSTK_ADD_TEXT_TO(const int8_t *rootId, const int8_t *content,
                                  const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_SYSTEM_IMAGE_TO(const int8_t *rootId,
                                          const int8_t *systemName,
                                          const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_BUTTON_TO(const int8_t *rootId, const int8_t *text,
                                    const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_SPACER(const int8_t *rootId, const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_DIVIDER(const int8_t *rootId, const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_BATCH(const int8_t *rootId, const int8_t *json,
                                const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_LIST(const int8_t *rootId, const int8_t *parentId);
const int8_t *SW_ZSTK_ADD_LAZYVGRID(const int8_t *rootId,
                                    const int8_t *parentId,
                                    const int8_t *columnsJson);

// List
void SW_LST_SET_SELECTION(const int8_t *rootId, const int8_t *indexStr);
void SW_LST_SET_BGCOLOR(const int8_t *rootId, const int8_t *r, const int8_t *g,
                        const int8_t *b, const int8_t *a);
