/*
#import <Foundation/Foundation.h>
#include <hbapi.h>
#include <hbapiitm.h>
#include <hbvm.h>

// This file is now redundant as all bridges have been migrated to @HarbourDirect
// or @HarbourBridge macros, and legacy wrappers are implemented in SwiftSystem.prg

// Direct bridge declarations generated by @HarbourDirect
extern void HB_FUN_SD_SW_GET_FILE(void * p);
extern void HB_FUN_SD_SW_GET_DIR(void * p);
extern void HB_FUN_SD_SW_ALERT(void * p);
extern void HB_FUN_SD_SW_MSG_YES_NO(void * p);
extern void HB_FUN_SD_SW_GET_COLOR(void * p);
extern void HB_FUN_SD_SW_GET_PATH(void * p);
extern void HB_FUN_SD_SW_GET_APP_PATH(void * p);
extern void HB_FUN_SD_SW_GET_RES_PATH(void * p);
extern void HB_FUN_SD_SW_GET_IMAGE(void * p);

// Observation Bridge (from SwiftMacro generated names)
extern void SW_OBS_SET_COUNT(const char *val);
extern void SW_OBS_SET_MSG(const char *nombre);
extern int sw_obs_get_count(void);

HB_FUNC(CSWGETFILE) { HB_FUN_SD_SW_GET_FILE(NULL); }

HB_FUNC(CSWGETDIR) { HB_FUN_SD_SW_GET_DIR(NULL); }

HB_FUNC(SW_MSGINFO) { HB_FUN_SD_SW_ALERT(NULL); }

HB_FUNC(SW_MSGYESNO) { HB_FUN_SD_SW_MSG_YES_NO(NULL); }

HB_FUNC(CSWGETCOLOR) { HB_FUN_SD_SW_GET_COLOR(NULL); }

HB_FUNC(CSWPATH) { HB_FUN_SD_SW_GET_PATH(NULL); }

HB_FUNC(CSWAPPPATH) { HB_FUN_SD_SW_GET_APP_PATH(NULL); }

HB_FUNC(CSWRESPATH) { HB_FUN_SD_SW_GET_RES_PATH(NULL); }

// Observation Bridge Functions (HB_FUNCs)
HB_FUNC(SW_OBS_SETCOUNT) { SW_OBS_SET_COUNT(hb_parc(1)); }

HB_FUNC(SW_OBS_SETMSG) { SW_OBS_SET_MSG(hb_parc(1)); }

HB_FUNC(SW_OBS_GETCOUNT) { hb_retni(sw_obs_get_count()); }

HB_FUNC(CSWGETIMAGEFILE) { HB_FUN_SD_SW_GET_IMAGE(NULL); }
*/
