#import <Cocoa/Cocoa.h>
#include <fivemac.h>

// Import the Swift header generated by the build process
#import "SwiftFive-Swift.h"

// Forward declarations of common helper functions
void SwiftMsgAlert(NSString *title, NSString *msg);
void setupSwiftView(NSView *swiftView, NSWindow *window, CGFloat x, CGFloat y,
                    CGFloat w, CGFloat h);
