/*
 * Harbour 3.2.0dev (r2512222342)
 * LLVM/Clang C 17.0 (clang-1700.6.3.2) ARM64
 * Generated C source from "../contrib/hbunix/hbunix.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( POSIX_CHDIR );
HB_FUNC_EXTERN( POSIX_ERRNO );
HB_FUNC_EXTERN( POSIX_GETEGID );
HB_FUNC_EXTERN( POSIX_GETEUID );
HB_FUNC_EXTERN( POSIX_GETGID );
HB_FUNC_EXTERN( POSIX_GETPID );
HB_FUNC_EXTERN( POSIX_GETUID );
HB_FUNC_EXTERN( POSIX_SETEGID );
HB_FUNC_EXTERN( POSIX_SETEUID );
HB_FUNC_EXTERN( POSIX_SETGID );
HB_FUNC_EXTERN( POSIX_SETUID );
HB_FUNC_EXTERN( POSIX_SLEEP );
HB_FUNC_EXTERN( UNIX_CHROOT );
HB_FUNC_EXTERN( UNIX_DAEMON );
HB_FUNC( __HBEXTERN__HBUNIX__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBUNIX )
{ "POSIX_CHDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_CHDIR )}, NULL },
{ "POSIX_ERRNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_ERRNO )}, NULL },
{ "POSIX_GETEGID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_GETEGID )}, NULL },
{ "POSIX_GETEUID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_GETEUID )}, NULL },
{ "POSIX_GETGID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_GETGID )}, NULL },
{ "POSIX_GETPID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_GETPID )}, NULL },
{ "POSIX_GETUID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_GETUID )}, NULL },
{ "POSIX_SETEGID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_SETEGID )}, NULL },
{ "POSIX_SETEUID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_SETEUID )}, NULL },
{ "POSIX_SETGID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_SETGID )}, NULL },
{ "POSIX_SETUID", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_SETUID )}, NULL },
{ "POSIX_SLEEP", {HB_FS_PUBLIC}, {HB_FUNCNAME( POSIX_SLEEP )}, NULL },
{ "UNIX_CHROOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( UNIX_CHROOT )}, NULL },
{ "UNIX_DAEMON", {HB_FS_PUBLIC}, {HB_FUNCNAME( UNIX_DAEMON )}, NULL },
{ "__HBEXTERN__HBUNIX__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBUNIX__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBUNIX, "../contrib/hbunix/hbunix.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBUNIX
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBUNIX )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBUNIX__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

