/*
 * Harbour 3.2.0dev (r2512222342)
 * LLVM/Clang C 17.0 (clang-1700.6.3.2) ARM64
 * Generated C source from "hbmysql/hbmysql.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( MYSQL_AFFECTED_ROWS );
HB_FUNC_EXTERN( MYSQL_COMMIT );
HB_FUNC_EXTERN( MYSQL_DATA_SEEK );
HB_FUNC_EXTERN( MYSQL_ERRNO );
HB_FUNC_EXTERN( MYSQL_ERROR );
HB_FUNC_EXTERN( MYSQL_ESCAPE_STRING );
HB_FUNC_EXTERN( MYSQL_ESCAPE_STRING_FROM_FILE );
HB_FUNC_EXTERN( MYSQL_FETCH_FIELD );
HB_FUNC_EXTERN( MYSQL_FETCH_ROW );
HB_FUNC_EXTERN( MYSQL_FIELD_COUNT );
HB_FUNC_EXTERN( MYSQL_FIELD_SEEK );
HB_FUNC_EXTERN( MYSQL_GET_HOST_INFO );
HB_FUNC_EXTERN( MYSQL_GET_SERVER_INFO );
HB_FUNC_EXTERN( MYSQL_GET_SERVER_VERSION );
HB_FUNC_EXTERN( MYSQL_INSERT_ID );
HB_FUNC_EXTERN( MYSQL_LIST_DBS );
HB_FUNC_EXTERN( MYSQL_LIST_FIELDS );
HB_FUNC_EXTERN( MYSQL_LIST_TABLES );
HB_FUNC_EXTERN( MYSQL_NUM_FIELDS );
HB_FUNC_EXTERN( MYSQL_NUM_ROWS );
HB_FUNC_EXTERN( MYSQL_PING );
HB_FUNC_EXTERN( MYSQL_QUERY );
HB_FUNC_EXTERN( MYSQL_REAL_CONNECT );
HB_FUNC_EXTERN( MYSQL_REAL_ESCAPE_STRING );
HB_FUNC_EXTERN( MYSQL_ROLLBACK );
HB_FUNC_EXTERN( MYSQL_SELECT_DB );
HB_FUNC_EXTERN( MYSQL_STORE_RESULT );
HB_FUNC_EXTERN( MYSQL_USE_RESULT );
HB_FUNC_EXTERN( TBCOLUMNSQL );
HB_FUNC_EXTERN( TBROWSESQL );
HB_FUNC_EXTERN( TMYSQLQUERY );
HB_FUNC_EXTERN( TMYSQLROW );
HB_FUNC_EXTERN( TMYSQLSERVER );
HB_FUNC_EXTERN( TMYSQLTABLE );
HB_FUNC( __HBEXTERN__HBMYSQL__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBMYSQL )
{ "MYSQL_AFFECTED_ROWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_AFFECTED_ROWS )}, NULL },
{ "MYSQL_COMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_COMMIT )}, NULL },
{ "MYSQL_DATA_SEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_DATA_SEEK )}, NULL },
{ "MYSQL_ERRNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_ERRNO )}, NULL },
{ "MYSQL_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_ERROR )}, NULL },
{ "MYSQL_ESCAPE_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_ESCAPE_STRING )}, NULL },
{ "MYSQL_ESCAPE_STRING_FROM_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_ESCAPE_STRING_FROM_FILE )}, NULL },
{ "MYSQL_FETCH_FIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_FETCH_FIELD )}, NULL },
{ "MYSQL_FETCH_ROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_FETCH_ROW )}, NULL },
{ "MYSQL_FIELD_COUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_FIELD_COUNT )}, NULL },
{ "MYSQL_FIELD_SEEK", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_FIELD_SEEK )}, NULL },
{ "MYSQL_GET_HOST_INFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_GET_HOST_INFO )}, NULL },
{ "MYSQL_GET_SERVER_INFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_GET_SERVER_INFO )}, NULL },
{ "MYSQL_GET_SERVER_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_GET_SERVER_VERSION )}, NULL },
{ "MYSQL_INSERT_ID", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_INSERT_ID )}, NULL },
{ "MYSQL_LIST_DBS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_LIST_DBS )}, NULL },
{ "MYSQL_LIST_FIELDS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_LIST_FIELDS )}, NULL },
{ "MYSQL_LIST_TABLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_LIST_TABLES )}, NULL },
{ "MYSQL_NUM_FIELDS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_NUM_FIELDS )}, NULL },
{ "MYSQL_NUM_ROWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_NUM_ROWS )}, NULL },
{ "MYSQL_PING", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_PING )}, NULL },
{ "MYSQL_QUERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_QUERY )}, NULL },
{ "MYSQL_REAL_CONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_REAL_CONNECT )}, NULL },
{ "MYSQL_REAL_ESCAPE_STRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_REAL_ESCAPE_STRING )}, NULL },
{ "MYSQL_ROLLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_ROLLBACK )}, NULL },
{ "MYSQL_SELECT_DB", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_SELECT_DB )}, NULL },
{ "MYSQL_STORE_RESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_STORE_RESULT )}, NULL },
{ "MYSQL_USE_RESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQL_USE_RESULT )}, NULL },
{ "TBCOLUMNSQL", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBCOLUMNSQL )}, NULL },
{ "TBROWSESQL", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBROWSESQL )}, NULL },
{ "TMYSQLQUERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( TMYSQLQUERY )}, NULL },
{ "TMYSQLROW", {HB_FS_PUBLIC}, {HB_FUNCNAME( TMYSQLROW )}, NULL },
{ "TMYSQLSERVER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TMYSQLSERVER )}, NULL },
{ "TMYSQLTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( TMYSQLTABLE )}, NULL },
{ "__HBEXTERN__HBMYSQL__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBMYSQL__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBMYSQL, "hbmysql/hbmysql.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBMYSQL
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBMYSQL )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBMYSQL__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

