// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef SWIFTFIVE_SWIFT_H
#define SWIFTFIVE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SwiftFive",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("SwiftButtonLoader")
@interface SwiftButtonLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSView;
SWIFT_CLASS_NAMED("SwiftChartLoader")
@interface SwiftChartLoader : NSObject
+ (NSView * _Nonnull)makeChart:(NSString * _Nonnull)id data:(NSString * _Nonnull)data type:(NSString * _Nonnull)type index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setData:(NSString * _Nonnull)data id:(NSString * _Nonnull)id;
+ (void)setType:(NSString * _Nonnull)type id:(NSString * _Nonnull)id;
+ (void)makeSnapshot:(NSString * _Nonnull)id path:(NSString * _Nonnull)path;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftDatePickerLoader")
@interface SwiftDatePickerLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftGridLoader")
@interface SwiftGridLoader : NSObject
+ (NSView * _Nonnull)makeGridWithIndex:(NSString * _Nonnull)index columnsJson:(NSString * _Nonnull)columnsJson SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftImageLoader")
@interface SwiftImageLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftLabelLoader")
@interface SwiftLabelLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftListLoader")
@interface SwiftListLoader : NSObject
+ (NSView * _Nonnull)makeListWithIndex:(NSString * _Nonnull)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (void)selectIndex:(NSString * _Nonnull)id index:(NSInteger)index;
+ (void)setBackgroundColorRed:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9SwiftFive11SwiftLoader")
@interface SwiftLoader : NSObject
+ (NSView * _Nonnull)makeView SWIFT_WARN_UNUSED_RESULT;
+ (NSView * _Nonnull)makeViewWithCallback:(void (^ _Nullable)(NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
+ (void)updateLabel:(NSString * _Nonnull)text;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftMusicLoader")
@interface SwiftMusicLoader : NSObject
+ (void)requestAuth;
+ (void)play;
+ (void)pause;
+ (void)next;
+ (void)previous;
+ (void)stop;
+ (NSInteger)getState SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getCurrentTrack SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getArtworkPath SWIFT_WARN_UNUSED_RESULT;
+ (double)getDuration SWIFT_WARN_UNUSED_RESULT;
+ (double)getPosition SWIFT_WARN_UNUSED_RESULT;
+ (void)setPositionWithSeconds:(double)seconds;
+ (NSInteger)getVolume SWIFT_WARN_UNUSED_RESULT;
+ (void)setVolumeWithVol:(NSInteger)vol;
+ (NSString * _Nonnull)getPlaylists SWIFT_WARN_UNUSED_RESULT;
+ (void)playPlaylistWithName:(NSString * _Nonnull)name;
+ (void)playFirstAvailablePlaylist;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftObservationLoader")
@interface SwiftObservationLoader : NSObject
+ (NSView * _Nonnull)makeObservationTest:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftPDF")
@interface SwiftPDF : NSObject
+ (void)saveView:(NSInteger)id to:(NSString * _Nonnull)path;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftPickerLoader")
@interface SwiftPickerLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftSliderLoader")
@interface SwiftSliderLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftSpeechManager")
@interface SwiftSpeechManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SwiftSpeechManager * _Nonnull shared;)
+ (SwiftSpeechManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable onTranscription)(NSString * _Nonnull, BOOL);
@property (nonatomic, copy) void (^ _Nullable onVocalMetrics)(double, double, double);
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
- (void)start;
- (void)recordToFile:(NSString * _Nonnull)path;
- (void)stopRecording;
- (void)transcribeFile:(NSString * _Nonnull)path;
- (void)stop;
- (void)setLocale:(NSString * _Nonnull)identifier;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftTabViewLoader")
@interface SwiftTabViewLoader : NSObject
+ (void)addTabWithIndex:(NSInteger)index title:(NSString * _Nonnull)title icon:(NSString * _Nonnull)icon;
+ (void)addTabWithId:(NSInteger)index title:(NSString * _Nonnull)title icon:(NSString * _Nonnull)icon;
+ (NSView * _Nonnull)makeTabView SWIFT_WARN_UNUSED_RESULT;
+ (void)clearTabs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftTextFieldLoader")
@interface SwiftTextFieldLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftToggleLoader")
@interface SwiftToggleLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftVStackLoader")
@interface SwiftVStackLoader : NSObject
+ (NSView * _Nonnull)makeVStackWithIndex:(NSString * _Nonnull)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (void)removeAllItems:(NSString * _Nonnull)rootId;
+ (NSString * _Nonnull)addItem:(NSString * _Nonnull)rootId content:(NSString * _Nonnull)content;
+ (NSString * _Nonnull)addTextItem:(NSString * _Nonnull)rootId content:(NSString * _Nonnull)content parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addSpacerItem:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addSystemImage:(NSString * _Nonnull)rootId systemName:(NSString * _Nonnull)systemName;
+ (NSString * _Nonnull)addSystemImageItem:(NSString * _Nonnull)rootId systemName:(NSString * _Nonnull)systemName parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addHStackItem:(NSString * _Nonnull)rootId text:(NSString * _Nonnull)text systemName:(NSString * _Nonnull)systemName;
+ (void)setScrollable:(NSString * _Nonnull)rootId scrollable:(BOOL)scrollable;
+ (void)setBackgroundColorRed:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setForegroundColorRed:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setSpacing:(NSString * _Nonnull)rootId spacing:(double)spacing;
+ (void)setAlignment:(NSString * _Nonnull)rootId alignment:(NSInteger)alignment;
+ (void)setInvertedColor:(NSString * _Nonnull)rootId useInverted:(BOOL)useInverted;
+ (void)setBackgroundColorHex:(NSString * _Nonnull)rootId hex:(NSString * _Nonnull)hex;
+ (void)setForegroundColorHex:(NSString * _Nonnull)rootId hex:(NSString * _Nonnull)hex;
+ (void)setLastItemId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id;
+ (NSString * _Nonnull)getLastItemId:(NSString * _Nonnull)rootId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addVStackItem:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addHStackContainer:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addLazyVGrid:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId columnsJson:(NSString * _Nonnull)columnsJson;
+ (NSString * _Nonnull)addList:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addTextItem:(NSString * _Nonnull)rootId text:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addSpacer:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addDivider:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addButtonItem:(NSString * _Nonnull)rootId text:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId;
+ (void)setItemText:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id text:(NSString * _Nonnull)text;
+ (void)setItem:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setItemLayout:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id w:(double)w h:(double)h s:(double)s;
+ (NSString * _Nonnull)addBatch:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId json:(NSString * _Nonnull)json;
+ (void)setActionCallback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (void)addItem:(NSString * _Nonnull)text;
+ (void)addSystemImage:(NSString * _Nonnull)systemName;
+ (void)addSystemImageItem:(NSString * _Nonnull)systemName parentId:(NSString * _Nullable)parentId;
+ (void)addHStackItem:(NSString * _Nonnull)text systemName:(NSString * _Nonnull)systemName;
+ (void)setScrollable:(BOOL)scrollable;
+ (void)setBackgroundColorRed:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setSpacing:(double)spacing;
+ (void)setAlignment:(NSInteger)alignment;
+ (void)setInvertedColor:(BOOL)useInverted;
+ (void)setLastItemId:(NSString * _Nonnull)id;
+ (NSString * _Nonnull)addVStackItem:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addHStackContainer:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addLazyVGrid:(NSString * _Nullable)parentId columnsJson:(NSString * _Nonnull)columnsJson SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addList:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addTextItem:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (void)addSpacer:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (void)addDivider:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addButtonItem:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (void)setItem:(NSString * _Nonnull)id backgroundColorRed:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (NSString * _Nonnull)addBatchToParent:(NSString * _Nullable)parentId json:(NSString * _Nonnull)json SWIFT_WARN_UNUSED_RESULT;
+ (void)setItemTextWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id text:(NSString * _Nonnull)text;
+ (void)setItemColorWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id r:(CGFloat)r g:(CGFloat)g b:(CGFloat)b a:(CGFloat)a;
+ (void)setItemFontWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id size:(CGFloat)size isBold:(BOOL)isBold;
+ (void)setItemRadiusWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id radius:(CGFloat)radius;
+ (void)setItemColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
+ (void)setItemBgColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftZStackLoader")
@interface SwiftZStackLoader : NSObject
+ (NSView * _Nonnull)makeZStackWithIndex:(NSString * _Nonnull)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (NSString * _Nonnull)addItem:(NSString * _Nonnull)rootId content:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addSystemImage:(NSString * _Nonnull)rootId systemName:(NSString * _Nonnull)systemName SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addFileImage:(NSString * _Nonnull)rootId filePath:(NSString * _Nonnull)filePath SWIFT_WARN_UNUSED_RESULT;
+ (void)removeAllItems:(NSString * _Nonnull)rootId;
+ (NSString * _Nonnull)addBatch:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId json:(NSString * _Nonnull)json SWIFT_WARN_UNUSED_RESULT;
+ (void)setAlignment:(NSString * _Nonnull)rootId alignment:(NSInteger)alignment;
+ (void)setBackgroundColor:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setForegroundColor:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setItemColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
+ (void)setItemBgColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("ViewRegistry")
@interface ViewRegistry : NSObject
+ (void)registerObject:(id _Nonnull)object forIndex:(NSInteger)index;
+ (id _Nullable)getObject:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
+ (void)clean:(NSInteger)index;
+ (void)registerNSView:(NSView * _Nonnull)view forIndex:(NSInteger)index;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_EXTERN void HB_FUN_SD_BTN_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_BG(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_FG(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_GLASS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_IMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_PADDING(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_RADIUS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_GET_DATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_SET_DATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_SET_ENABLED(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_ASPECT_RATIO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_COLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_FILE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_NAME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_NSIMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_RESIZABLE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_SYSTEM_NAME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_ALIGN(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_COLORS_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_COLORS_RGBA(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_FONT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_FONT_STYLE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_LST_REMOVE_ALL(int8_t const * _Nullable p0) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_LST_SET_BGCOLOR(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2, int8_t const * _Nullable p3, int8_t const * _Nullable p4) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_LST_SET_BGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_LST_SET_SELECTION(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_OBS_SET_COUNT(int8_t const * _Nullable p0) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_OBS_SET_MSG(int8_t const * _Nullable p0) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_GET_SELECTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_GLASS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_ITEMS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_PLACEHOLDER(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_SELECTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_SHOW_LABEL(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_TITLE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_GET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_SET_ACCENT_COLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_SET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_BUTTON_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_DATEPICKER_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN int8_t const * _Nullable swift_get_app_path(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable swift_get_dir(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable swift_get_file(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable swift_get_image(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable swift_get_path(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable swift_get_res_path(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_IMAGE_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_LABEL_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_PICKER_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_SLIDER_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TEXTEDITOR_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TEXTFIELD_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TOGGLE_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_GET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_SET_FONT_SIZE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_SET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_GET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_CAPTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_COLORS_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_COLORS_RGBA(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_BATCH(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_BUTTON_ITEM(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_DIVIDER_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_HSTACK(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_ITEM(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_LAZYVGRID(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_LIST(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_SPACER_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_SYSTEM_IMAGE_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_TEXT_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_ADD_VSTACK(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_VSTK_GET_LAST_ITEM_ID(int8_t const * _Nullable p0) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN void SW_VSTK_REMOVE_ALL(int8_t const * _Nullable p0) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ALIGNMENT(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_BGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_FGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_INVERTED_COLOR(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ITEM_BGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ITEM_COLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ITEM_FONT(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2, int8_t const * _Nullable p3) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ITEM_LAYOUT(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2, int8_t const * _Nullable p3, int8_t const * _Nullable p4) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ITEM_RADIUS(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_ITEM_TEXT(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_SCROLL(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_VSTK_SET_SPACING(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_BATCH(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_BUTTON_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_DIVIDER(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_FILE_IMAGE(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_ITEM(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_LAZYVGRID(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_LIST(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_SPACER(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_SYSTEM_IMAGE_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable SW_ZSTK_ADD_TEXT_TO(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN void SW_ZSTK_REMOVE_ALL(int8_t const * _Nullable p0) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_ZSTK_SET_ALIGNMENT(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_ZSTK_SET_BGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_ZSTK_SET_FGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_ZSTK_SET_ITEM_BGCOLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT;

SWIFT_EXTERN void SW_ZSTK_SET_ITEM_COLOR_HEX(int8_t const * _Nullable p0, int8_t const * _Nullable p1, int8_t const * _Nullable p2) SWIFT_NOEXCEPT;

SWIFT_EXTERN int8_t const * _Nullable sw_GetRootId_par(int32_t iParam) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN NSInteger sw_obs_get_count(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN BOOL sw_obs_get_enabled(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN double sw_obs_get_level(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN int8_t const * _Nullable sw_parc(int32_t iParam) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN BOOL sw_parl(int32_t iParam) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN void swift_alert(int8_t const * _Nullable msg, int8_t const * _Nullable title, NSInteger type) SWIFT_NOEXCEPT;

SWIFT_EXTERN NSInteger swift_get_color(void) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN BOOL swift_msg_yes_no(int8_t const * _Nullable msg, int8_t const * _Nullable title) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
