// Generated by Apple Swift version 6.3 effective-5.10 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef SWIFTFIVE_SWIFT_H
#define SWIFTFIVE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SwiftFive",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SwiftFive",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS_NAMED("SwiftButtonLoader")
@interface SwiftButtonLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class NSView;
SWIFT_CLASS_NAMED("SwiftChartLoader")
@interface SwiftChartLoader : NSObject
+ (NSView * _Nonnull)makeChart:(NSString * _Nonnull)id data:(NSString * _Nonnull)data type:(NSString * _Nonnull)type index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setData:(NSString * _Nonnull)data id:(NSString * _Nonnull)id;
+ (void)setType:(NSString * _Nonnull)type id:(NSString * _Nonnull)id;
+ (void)makeSnapshot:(NSString * _Nonnull)id path:(NSString * _Nonnull)path;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftDatePickerLoader")
@interface SwiftDatePickerLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftGridLoader")
@interface SwiftGridLoader : NSObject
+ (NSView * _Nonnull)makeGridWithIndex:(NSString * _Nonnull)id columnsJson:(NSString * _Nonnull)columnsJson SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftImageLoader")
@interface SwiftImageLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftLabelLoader")
@interface SwiftLabelLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftListLoader")
@interface SwiftListLoader : NSObject
+ (NSView * _Nonnull)makeListWithIndex:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (void)selectIndex:(NSString * _Nonnull)id index:(NSInteger)index;
+ (void)setBackgroundColorRed:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setItemLayout:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id w:(NSString * _Nonnull)w h:(NSString * _Nonnull)h s:(NSString * _Nonnull)s;
+ (void)setItemFont:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id size:(NSString * _Nonnull)size isBold:(BOOL)isBold;
+ (void)setItemColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
+ (void)setItemBgColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
+ (void)setItemText:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id text:(NSString * _Nonnull)text;
+ (void)setItemRadius:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id radius:(double)radius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9SwiftFive11SwiftLoader")
@interface SwiftLoader : NSObject
+ (NSView * _Nonnull)makeView SWIFT_WARN_UNUSED_RESULT;
+ (NSView * _Nonnull)makeViewWithCallback:(void (^ _Nullable)(NSString * _Nonnull))callback SWIFT_WARN_UNUSED_RESULT;
+ (void)updateLabel:(NSString * _Nonnull)text;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9SwiftFive16SwiftMusicLoader")
@interface SwiftMusicLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftObservationLoader")
@interface SwiftObservationLoader : NSObject
+ (NSView * _Nonnull)makeObservationTest:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftPDF")
@interface SwiftPDF : NSObject
+ (void)saveViewWithIndex:(NSInteger)index to:(NSString * _Nonnull)path;
+ (void)saveView:(NSString * _Nonnull)id to:(NSString * _Nonnull)path;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftPickerLoader")
@interface SwiftPickerLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftSliderLoader")
@interface SwiftSliderLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9SwiftFive18SwiftSpeechManager")
@interface SwiftSpeechManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftTabViewLoader")
@interface SwiftTabViewLoader : NSObject
+ (void)addTabWithIndex:(NSInteger)index title:(NSString * _Nonnull)title icon:(NSString * _Nonnull)icon;
+ (NSView * _Nonnull)makeTabView SWIFT_WARN_UNUSED_RESULT;
+ (void)clearTabs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftTextFieldLoader")
@interface SwiftTextFieldLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftToggleLoader")
@interface SwiftToggleLoader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftVStackLoader")
@interface SwiftVStackLoader : NSObject
+ (NSView * _Nonnull)makeVStackWithIndex:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (void)removeAllItems:(NSString * _Nonnull)rootId;
+ (NSString * _Nonnull)addItem:(NSString * _Nonnull)rootId content:(NSString * _Nonnull)content;
+ (NSString * _Nonnull)addTextItem:(NSString * _Nonnull)rootId content:(NSString * _Nonnull)content parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addSpacerItem:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addSystemImage:(NSString * _Nonnull)rootId systemName:(NSString * _Nonnull)systemName;
+ (NSString * _Nonnull)addSystemImageItem:(NSString * _Nonnull)rootId systemName:(NSString * _Nonnull)systemName parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addHStackItem:(NSString * _Nonnull)rootId text:(NSString * _Nonnull)text systemName:(NSString * _Nonnull)systemName;
+ (void)setScrollable:(NSString * _Nonnull)rootId scrollable:(BOOL)scrollable;
+ (void)setBackgroundColorRed:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setForegroundColorRed:(NSString * _Nonnull)rootId red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setSpacing:(NSString * _Nonnull)rootId spacing:(double)spacing;
+ (void)setAlignment:(NSString * _Nonnull)rootId alignment:(NSInteger)alignment;
+ (void)setInvertedColor:(NSString * _Nonnull)rootId useInverted:(BOOL)useInverted;
+ (void)setBackgroundColorHex:(NSString * _Nonnull)rootId hex:(NSString * _Nonnull)hex;
+ (void)setForegroundColorHex:(NSString * _Nonnull)rootId hex:(NSString * _Nonnull)hex;
+ (void)setLastItemId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id;
+ (NSString * _Nonnull)getLastItemId:(NSString * _Nonnull)rootId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addStackItem:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addHStackContainer:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addLazyVGrid:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId columnsJson:(NSString * _Nonnull)columnsJson;
+ (NSString * _Nonnull)addList:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addTextItem:(NSString * _Nonnull)rootId text:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addSpacer:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addDivider:(NSString * _Nonnull)rootId dummy:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addButtonItem:(NSString * _Nonnull)rootId text:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId;
+ (void)setItemText:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id text:(NSString * _Nonnull)text;
+ (void)setItem:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id red:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setItemLayout:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id w:(double)w h:(double)h s:(double)s;
+ (NSString * _Nonnull)addBatch:(NSString * _Nonnull)rootId parentId:(NSString * _Nullable)parentId json:(NSString * _Nonnull)json;
+ (void)setActionCallback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
+ (void)addItem:(NSString * _Nonnull)text;
+ (void)addSystemImage:(NSString * _Nonnull)systemName;
+ (void)addSystemImageItem:(NSString * _Nonnull)systemName parentId:(NSString * _Nullable)parentId;
+ (void)addHStackItem:(NSString * _Nonnull)text systemName:(NSString * _Nonnull)systemName;
+ (void)setScrollable:(BOOL)scrollable;
+ (void)setBackgroundColorRed:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (void)setSpacing:(double)spacing;
+ (void)setAlignment:(NSInteger)alignment;
+ (void)setInvertedColor:(BOOL)useInverted;
+ (void)setLastItemId:(NSString * _Nonnull)id;
+ (NSString * _Nonnull)addStackItem:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addHStackContainer:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addLazyVGrid:(NSString * _Nullable)parentId columnsJson:(NSString * _Nonnull)columnsJson SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addList:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)addTextItem:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (void)addSpacer:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (void)addDivider:(NSString * _Nonnull)dummy parentId:(NSString * _Nullable)parentId;
+ (NSString * _Nonnull)addButtonItem:(NSString * _Nonnull)text parentId:(NSString * _Nullable)parentId SWIFT_WARN_UNUSED_RESULT;
+ (void)setItem:(NSString * _Nonnull)id backgroundColorRed:(double)red green:(double)green blue:(double)blue alpha:(double)alpha;
+ (NSString * _Nonnull)addBatchToParent:(NSString * _Nullable)parentId json:(NSString * _Nonnull)json SWIFT_WARN_UNUSED_RESULT;
+ (void)setItemTextWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id text:(NSString * _Nonnull)text;
+ (void)setItemColorWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id r:(CGFloat)r g:(CGFloat)g b:(CGFloat)b a:(CGFloat)a;
+ (void)setItemFontWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id size:(CGFloat)size isBold:(BOOL)isBold;
+ (void)setItemRadiusWithRootId:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id radius:(CGFloat)radius;
+ (void)setItemColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
+ (void)setItemBgColor:(NSString * _Nonnull)rootId id:(NSString * _Nonnull)id hex:(NSString * _Nonnull)hex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftWebViewLoader")
@interface SwiftWebViewLoader : NSObject
+ (NSView * _Nonnull)makeWebViewWithId:(NSString * _Nullable)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("SwiftZStackLoader")
@interface SwiftZStackLoader : NSObject
+ (NSView * _Nonnull)makeZStackWithIndex:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
+ (void)setActionCallbackWithRootId:(NSString * _Nonnull)rootId callback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_EXTERN void HB_FUN_SD_BTN_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_BG(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_FG(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_GLASS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_IMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_PADDING(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_RADIUS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_BTN_SET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_CHART_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_CHART_MAKE_SNAPSHOT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_CHART_SET_DATA(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_CHART_SET_TITLES(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_CHART_SET_TYPE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_GET_DATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_SET_DATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_DTP_SET_ENABLED(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_ASPECT_RATIO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_COLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_FILE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_NAME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_NSIMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_RESIZABLE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_IMG_SET_SYSTEM_NAME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_ALIGN(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_COLORS_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_COLORS_RGBA(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_FONT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_FONT_STYLE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LBL_SET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_ADD_BATCH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_ADD_ITEM(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_ADD_ROW(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_GET_LAST_ITEM_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_REMOVE_ALL(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_BGCOLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_BGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_ITEM_BGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_ITEM_COLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_ITEM_FONT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_ITEM_LAYOUT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_ITEM_RADIUS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_ITEM_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_LST_SET_SELECTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_AUTH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_GET_ARTWORK(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_GET_DURATION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_GET_PLAYLISTS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_GET_POSITION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_GET_VOLUME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_METADATA(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_NEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_PAUSE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_PLAY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_PLAY_FIRST(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_PLAY_PLAYLIST(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_PREV(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_SET_POSITION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_SET_VOLUME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_STATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_MUSIC_STOP(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_OBS_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_OBS_GET_COUNT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_OBS_GET_ENABLED(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_OBS_GET_LEVEL(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_OBS_SET_COUNT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_OBS_SET_MSG(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_GET_SELECTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_ARRAY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_GLASS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_ITEMS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_PLACEHOLDER(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_SELECTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_SHOW_LABEL(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_PKR_SET_TITLE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_GET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_SET_ACCENT_COLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SLD_SET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SPEECH_RECORD_FILE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SPEECH_SET_LOCALE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SPEECH_START(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SPEECH_STOP(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SPEECH_STOP_RECORDING(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SPEECH_TRANSCRIBE_FILE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_ALERT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GETIP(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_APP_PATH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_COLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_DIR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_FILE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_IMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_PATH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_GET_RES_PATH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_CAN_RESUME(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_CLEAR_HEADERS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_DELETE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_DOWNLOAD_ASYNC(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_GET(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_GET_JSON(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_POST(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_PUT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_SET_HEADER(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_UPLOAD(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_HTTP_WAIT_DOWNLOAD(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_ISCONNECTED(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_MSG_YES_NO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_EVAL(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_EVAL_ARG(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_GO_BACK(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_GO_FORWARD(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_IS_LOADING(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_LOAD(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_LOAD_FILE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_LOAD_HTML(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_PROGRESS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_RELOAD(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_SAVE_PDF(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_SET_ZOOM(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SW_WEBVIEW_STOP(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_BUTTON_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_CHART_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_DATEPICKER_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_GRID_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_IMAGE_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_LABEL_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_LIST_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_OBSERVATION_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_PDF_SAVE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_PICKER_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_SLIDER_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TABVIEW_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TEXTEDITOR_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TEXTFIELD_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_TOGGLE_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_VSTACK_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_SWIFT_ZSTACK_CREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TAB_ADD(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TAB_CLEAR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TAB_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_GET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_SET_COLORS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_SET_FONT_SIZE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TF_SET_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_GET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_CAPTION(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_COLORS_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_COLORS_RGBA(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_TGL_SET_VALUE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_BATCH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_BUTTON_ITEM(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_DIVIDER_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_HSTACK(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_ITEM(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_LAZYVGRID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_LIST(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_SPACER_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_SYSTEM_IMAGE_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_TEXT_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_ADD_VSTACK(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_GET_LAST_ITEM_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_REMOVE_ALL_ITEMS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ALIGNMENT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_BGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_FGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_INVERTED_COLOR(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ITEM_BGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ITEM_COLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ITEM_FONT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ITEM_LAYOUT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ITEM_RADIUS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_ITEM_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_LAST_ITEM_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_SCROLL(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_VSTK_SET_SPACING(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_BATCH(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_BUTTON_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_DIVIDER(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_FILE_IMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_HSTACK(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_IMAGE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_ITEM(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_LAZYVGRID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_LIST(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_SPACER(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_SYSTEM_IMAGE_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_TEXT_TO(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_ADD_VSTACK(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_DESTROY(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_GET_LAST_ITEM_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_REMOVE_ALL_ITEMS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ALIGNMENT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_BGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_FGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ITEM_BGCOLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ITEM_COLOR_HEX(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ITEM_FONT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ITEM_LAYOUT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ITEM_RADIUS(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_ITEM_TEXT(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SD_ZSTK_SET_LAST_ITEM_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_CREATESWIFTVIEW(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN int8_t const * _Nullable sw_GetRootId_par(int32_t iParam) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN void HB_FUN_SW_GET_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN BOOL sw_parl(int32_t iParam) SWIFT_NOEXCEPT SWIFT_WARN_UNUSED_RESULT;

SWIFT_EXTERN void HB_FUN_SW_SET_ID(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SWIFTAUTORESIZE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SWIFTSTANDALONEBATCHCREATE(void * _Nullable p) SWIFT_NOEXCEPT;

SWIFT_EXTERN void HB_FUN_SWIFT_UUID(void * _Nullable p) SWIFT_NOEXCEPT;

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
