/*
 * Harbour 3.2.0dev (r2512222342)
 * LLVM/Clang C 17.0 (clang-1700.6.3.2) ARM64
 * Generated C source from "hbcurl/hbcurl.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( CURL_EASY_CLEANUP );
HB_FUNC_EXTERN( CURL_EASY_DL_BUFF_GET );
HB_FUNC_EXTERN( CURL_EASY_DUPLICATE );
HB_FUNC_EXTERN( CURL_EASY_ER_BUFF_GET );
HB_FUNC_EXTERN( CURL_EASY_ESCAPE );
HB_FUNC_EXTERN( CURL_EASY_GETINFO );
HB_FUNC_EXTERN( CURL_EASY_INIT );
HB_FUNC_EXTERN( CURL_EASY_PAUSE );
HB_FUNC_EXTERN( CURL_EASY_PERFORM );
HB_FUNC_EXTERN( CURL_EASY_RECV );
HB_FUNC_EXTERN( CURL_EASY_RESET );
HB_FUNC_EXTERN( CURL_EASY_SEND );
HB_FUNC_EXTERN( CURL_EASY_SETOPT );
HB_FUNC_EXTERN( CURL_EASY_STRERROR );
HB_FUNC_EXTERN( CURL_EASY_UNESCAPE );
HB_FUNC_EXTERN( CURL_ESCAPE );
HB_FUNC_EXTERN( CURL_GETDATE );
HB_FUNC_EXTERN( CURL_GLOBAL_CLEANUP );
HB_FUNC_EXTERN( CURL_GLOBAL_INIT );
HB_FUNC_EXTERN( CURL_MULTI_ADD_HANDLE );
HB_FUNC_EXTERN( CURL_MULTI_CLEANUP );
HB_FUNC_EXTERN( CURL_MULTI_INFO_READ );
HB_FUNC_EXTERN( CURL_MULTI_INIT );
HB_FUNC_EXTERN( CURL_MULTI_PERFORM );
HB_FUNC_EXTERN( CURL_MULTI_POLL );
HB_FUNC_EXTERN( CURL_MULTI_REMOVE_HANDLE );
HB_FUNC_EXTERN( CURL_UNESCAPE );
HB_FUNC_EXTERN( CURL_VERSION );
HB_FUNC_EXTERN( CURL_VERSION_INFO );
HB_FUNC_EXTERN( CURL_WS_RECV );
HB_FUNC_EXTERN( CURL_WS_SEND );
HB_FUNC( __HBEXTERN__HBCURL__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBCURL )
{ "CURL_EASY_CLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_CLEANUP )}, NULL },
{ "CURL_EASY_DL_BUFF_GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_DL_BUFF_GET )}, NULL },
{ "CURL_EASY_DUPLICATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_DUPLICATE )}, NULL },
{ "CURL_EASY_ER_BUFF_GET", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_ER_BUFF_GET )}, NULL },
{ "CURL_EASY_ESCAPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_ESCAPE )}, NULL },
{ "CURL_EASY_GETINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_GETINFO )}, NULL },
{ "CURL_EASY_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_INIT )}, NULL },
{ "CURL_EASY_PAUSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_PAUSE )}, NULL },
{ "CURL_EASY_PERFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_PERFORM )}, NULL },
{ "CURL_EASY_RECV", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_RECV )}, NULL },
{ "CURL_EASY_RESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_RESET )}, NULL },
{ "CURL_EASY_SEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_SEND )}, NULL },
{ "CURL_EASY_SETOPT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_SETOPT )}, NULL },
{ "CURL_EASY_STRERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_STRERROR )}, NULL },
{ "CURL_EASY_UNESCAPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_EASY_UNESCAPE )}, NULL },
{ "CURL_ESCAPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_ESCAPE )}, NULL },
{ "CURL_GETDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_GETDATE )}, NULL },
{ "CURL_GLOBAL_CLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_GLOBAL_CLEANUP )}, NULL },
{ "CURL_GLOBAL_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_GLOBAL_INIT )}, NULL },
{ "CURL_MULTI_ADD_HANDLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_ADD_HANDLE )}, NULL },
{ "CURL_MULTI_CLEANUP", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_CLEANUP )}, NULL },
{ "CURL_MULTI_INFO_READ", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_INFO_READ )}, NULL },
{ "CURL_MULTI_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_INIT )}, NULL },
{ "CURL_MULTI_PERFORM", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_PERFORM )}, NULL },
{ "CURL_MULTI_POLL", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_POLL )}, NULL },
{ "CURL_MULTI_REMOVE_HANDLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_MULTI_REMOVE_HANDLE )}, NULL },
{ "CURL_UNESCAPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_UNESCAPE )}, NULL },
{ "CURL_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_VERSION )}, NULL },
{ "CURL_VERSION_INFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_VERSION_INFO )}, NULL },
{ "CURL_WS_RECV", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_WS_RECV )}, NULL },
{ "CURL_WS_SEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURL_WS_SEND )}, NULL },
{ "__HBEXTERN__HBCURL__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBCURL__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBCURL, "hbcurl/hbcurl.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBCURL
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBCURL )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBCURL__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

