/*
 * Harbour 3.2.0dev (r2512222342)
 * LLVM/Clang C 17.0 (clang-1700.6.3.2) ARM64
 * Generated C source from "hbbmp/hbbmp.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( HB_BMP_COLOR );
HB_FUNC_EXTERN( HB_BMP_COLOR2RGB );
HB_FUNC_EXTERN( HB_BMP_COLORRESET );
HB_FUNC_EXTERN( HB_BMP_COPY );
HB_FUNC_EXTERN( HB_BMP_DECODE );
HB_FUNC_EXTERN( HB_BMP_DEPTH );
HB_FUNC_EXTERN( HB_BMP_ENCODE );
HB_FUNC_EXTERN( HB_BMP_ERROR );
HB_FUNC_EXTERN( HB_BMP_FREE );
HB_FUNC_EXTERN( HB_BMP_FROMBITMAP );
HB_FUNC_EXTERN( HB_BMP_GETPIXEL );
HB_FUNC_EXTERN( HB_BMP_HEIGHT );
HB_FUNC_EXTERN( HB_BMP_LINE );
HB_FUNC_EXTERN( HB_BMP_LOAD );
HB_FUNC_EXTERN( HB_BMP_NEW );
HB_FUNC_EXTERN( HB_BMP_PUTPIXEL );
HB_FUNC_EXTERN( HB_BMP_RECT );
HB_FUNC_EXTERN( HB_BMP_SAVE );
HB_FUNC_EXTERN( HB_BMP_WIDTH );
HB_FUNC( __HBEXTERN__HBBMP__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HBBMP )
{ "HB_BMP_COLOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_COLOR )}, NULL },
{ "HB_BMP_COLOR2RGB", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_COLOR2RGB )}, NULL },
{ "HB_BMP_COLORRESET", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_COLORRESET )}, NULL },
{ "HB_BMP_COPY", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_COPY )}, NULL },
{ "HB_BMP_DECODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_DECODE )}, NULL },
{ "HB_BMP_DEPTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_DEPTH )}, NULL },
{ "HB_BMP_ENCODE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_ENCODE )}, NULL },
{ "HB_BMP_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_ERROR )}, NULL },
{ "HB_BMP_FREE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_FREE )}, NULL },
{ "HB_BMP_FROMBITMAP", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_FROMBITMAP )}, NULL },
{ "HB_BMP_GETPIXEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_GETPIXEL )}, NULL },
{ "HB_BMP_HEIGHT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_HEIGHT )}, NULL },
{ "HB_BMP_LINE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_LINE )}, NULL },
{ "HB_BMP_LOAD", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_LOAD )}, NULL },
{ "HB_BMP_NEW", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_NEW )}, NULL },
{ "HB_BMP_PUTPIXEL", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_PUTPIXEL )}, NULL },
{ "HB_BMP_RECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_RECT )}, NULL },
{ "HB_BMP_SAVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_SAVE )}, NULL },
{ "HB_BMP_WIDTH", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_BMP_WIDTH )}, NULL },
{ "__HBEXTERN__HBBMP__", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__HBBMP__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_HBBMP, "hbbmp/hbbmp.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_HBBMP
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_HBBMP )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__HBBMP__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

